### ISSUE TITLE
Search is not working

### ISSUE THREAD

**Issue by MartLintz** [Raival-e/File-Explorer#19]
`[07/16/2022 17:13:42.791][Error][AppCrash]:  
java.lang.OutOfMemoryError: Failed to allocate a 537919496 byte allocation with 25165824 free bytes and 251MB until OOM, max allowed footprint 297940192, growth limit 536870912
	at java.util.Arrays.copyOf(Arrays.java:3260)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:451)
	at java.lang.StringBuilder.append(StringBuilder.java:137)
	at com.raival.fileexplorer.tab.file.util.FileUtils.readFile(FileUtils.java:364)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:148)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:177)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:177)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:177)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.lambda$onViewCreated$1$com-raival-fileexplorer-tab-file-dialog-SearchDialog(SearchDialog.java:118)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:764)
`

**Comment by Raival-e** [comment]
I managed to reproduce it, I'll try to fix it soon.
Thanks for reporting

**Comment by Raival-e** [comment]
This issue should be solved now, could you check?

**Comment by Raival-e** [comment]
It isn't, use Deep search to search inside files (it will read files contents). If you want to find files that ends with .zip, uncheck Deep search (you can also check Suffix for better results)

**Comment by Raival-e** [comment]
could you open a new issue and provide more information (when and how to reproduce it).
