### ISSUE TITLE
This happen suddenly ,when I am searching file . And then click results file to show error. 

### ISSUE THREAD

**Issue by MartLintz** [Raival-e/File-Explorer#20]
```
[07/16/2022 21:48:19.899][Error][AppCrash]:  
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.raival.fileexplorer.tab.file.FileExplorerTabFragment$IconResolver.lambda$start$1$com-raival-fileexplorer-tab-file-FileExplorerTabFragment$IconResolver(FileExplorerTabFragment.java:559)
	at com.raival.fileexplorer.tab.file.FileExplorerTabFragment$IconResolver$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.lang.Thread.run(Thread.java:919)

[07/17/2022 05:44:56.721][Error][AppCrash]:  
java.lang.OutOfMemoryError: Failed to allocate a 130334152 byte allocation with 25149440 free bytes and 122MB until OOM, target footprint 165239048, growth limit 268435456
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:260)
	at java.lang.StringBuilder.toString(StringBuilder.java:413)
	at com.raival.fileexplorer.tab.file.util.FileUtils.readFile(FileUtils.java:373)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:150)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:180)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:180)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.searchIn(SearchDialog.java:180)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog.lambda$onViewCreated$1$com-raival-fileexplorer-tab-file-dialog-SearchDialog(SearchDialog.java:119)
	at com.raival.fileexplorer.tab.file.dialog.SearchDialog$$ExternalSyntheticLambda3.run(Unknown Source:2)
	at java.lang.Thread.run(Thread.java:919)

```

_Originally posted by @MartLintz in https://github.com/Raival-e/File-Explorer/issues/19#issuecomment-1186351022_

**Comment by Raival-e** [comment]
Well, the first error (the one related to IconResolver) has already been fixed. For OutOfMemoryError, in settings, you should reduce the deep search file size limit (I recommend 6mb) in order to solve the issue.

**Comment by Raival-e** [comment]
I will close this issue, if you encounter the same issue after reducing the file size limit, please reopen the issue and I'll look further into it.

**Comment by Raival-e** [comment]
Update: I've added a new option to optimise searching that allows reading files line by line instead of reading the whole content. See commit 1b01ee5d45175fb7c96518bea78d55bbd793132c
