### ISSUE TITLE
Crash when changing theme

### ISSUE THREAD

**Issue by LetsDoNothing** [Raival-e/File-Explorer#27]
```[07/28/2022 20:19:07.332][Error][AppCrash]:  
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.raival.fileexplorer/com.raival.fileexplorer.activity.SettingsActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.raival.fileexplorer.common.dialog.OptionsDialog: could not find Fragment constructor
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3093)
	at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4887)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4770)
	at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ClientTransactionHandler.executeTransaction(ClientTransactionHandler.java:55)
	at android.app.ActivityThread.handleRelaunchActivityLocally(ActivityThread.java:4821)
	at android.app.ActivityThread.access$3200(ActivityThread.java:204)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1826)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6865)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.raival.fileexplorer.common.dialog.OptionsDialog: could not find Fragment constructor
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:628)
	at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
	at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:483)
	at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:85)
	at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2728)
	at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:198)
	at androidx.fragment.app.FragmentActivity$2.onContextAvailable(FragmentActivity.java:149)
	at androidx.activity.contextaware.ContextAwareHelper.dispatchOnContextAvailable(ContextAwareHelper.java:99)
	at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:322)
	at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:273)
	at com.raival.fileexplorer.activity.BaseActivity.onCreate(BaseActivity.java:39)
	at com.raival.fileexplorer.activity.SettingsActivity.onCreate(SettingsActivity.java:36)
	at android.app.Activity.performCreate(Activity.java:8606)
	at android.app.Activity.performCreate(Activity.java:8597)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1274)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2923)
	... 16 more
Caused by: java.lang.NoSuchMethodException: <init> []
	at java.lang.Class.getConstructor0(Class.java:2327)
	at java.lang.Class.getConstructor(Class.java:1725)
	at androidx.fragment.app.Fragment.instantiate(Fragment.java:613)
	... 31 more```

**Comment by Raival-e** [comment]
What android version do you use?

**Comment by Raival-e** [comment]
You use the latest build right?

**Comment by Raival-e** [comment]
Alright thanks, I'll look into it

**Comment by Raival-e** [comment]
What are the steps to reproduce the issue?

**Comment by Raival-e** [comment]
I couldn't reproduce it in the emulator running on Android 9

**Comment by Raival-e** [comment]
So it only happened once and doesn't occur anymore in the same device?
